<?php
$models = [
    'Business' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\n\nclass Business extends Model\n{\n    use HasFactory;\n\n    protected \$fillable = ['name', 'slug', 'description', 'logo_url'];\n\n    public function users() { return \$this->hasMany(User::class); }\n    public function wallet() { return \$this->hasOne(MerchantWallet::class); }\n    public function transactions() { return \$this->hasMany(Transaction::class); }\n    public function catalogCategories() { return \$this->hasMany(CatalogCategory::class); }\n    public function catalogItems() { return \$this->hasMany(CatalogItem::class); }\n    public function bookings() { return \$this->hasMany(Booking::class); }\n    public function queues() { return \$this->hasMany(Queue::class); }\n}\n",
    'MerchantWallet' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Model;\n\nclass MerchantWallet extends Model\n{\n    protected \$fillable = ['business_id', 'balance'];\n\n    public function business() { return \$this->belongsTo(Business::class); }\n    public function walletTransactions() { return \$this->hasMany(WalletTransaction::class); }\n}\n",
    'WalletTransaction' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Model;\n\nclass WalletTransaction extends Model\n{\n    protected \$fillable = ['merchant_wallet_id', 'type', 'amount', 'reference_id', 'description'];\n\n    public function wallet() { return \$this->belongsTo(MerchantWallet::class, 'merchant_wallet_id'); }\n}\n",
    'Transaction' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Model;\n\nclass Transaction extends Model\n{\n    protected \$fillable = ['business_id', 'transaction_number', 'total_amount', 'status', 'payment_method', 'idempotency_key'];\n\n    public function business() { return \$this->belongsTo(Business::class); }\n    public function platformFee() { return \$this->hasOne(PlatformFee::class); }\n}\n",
    'PlatformFee' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Model;\n\nclass PlatformFee extends Model\n{\n    protected \$fillable = ['business_id', 'transaction_id', 'amount'];\n\n    public function business() { return \$this->belongsTo(Business::class); }\n    public function transaction() { return \$this->belongsTo(Transaction::class); }\n}\n",
    'CatalogCategory' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Model;\n\nclass CatalogCategory extends Model\n{\n    protected \$fillable = ['business_id', 'name'];\n\n    public function business() { return \$this->belongsTo(Business::class); }\n    public function items() { return \$this->hasMany(CatalogItem::class, 'category_id'); }\n}\n",
    'CatalogItem' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Model;\n\nclass CatalogItem extends Model\n{\n    protected \$fillable = ['business_id', 'category_id', 'name', 'description', 'price', 'image_url', 'is_available'];\n\n    public function business() { return \$this->belongsTo(Business::class); }\n    public function category() { return \$this->belongsTo(CatalogCategory::class); }\n}\n",
    'Booking' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Model;\n\nclass Booking extends Model\n{\n    protected \$fillable = ['business_id', 'customer_name', 'customer_phone', 'booking_date', 'booking_time', 'guest_count', 'table_number', 'status'];\n\n    public function business() { return \$this->belongsTo(Business::class); }\n}\n",
    'Queue' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Model;\n\nclass Queue extends Model\n{\n    protected \$fillable = ['business_id', 'transaction_id', 'queue_number', 'queue_date', 'status'];\n\n    public function business() { return \$this->belongsTo(Business::class); }\n    public function transaction() { return \$this->belongsTo(Transaction::class); }\n}\n"
];

foreach ($models as $name => $content) {
    file_put_contents(__DIR__ . "/app/Models/{$name}.php", $content);
}
echo "Models generated.\n";
